version: '3.8'
services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=abner
      - DB_PASSWORD=1234
      - DB_NAME=lucas_db
      - APPLICATION_PORT=3001
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: lucas_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
